{
 "title": "1C APDEX metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(onec_info_connection_status,host)"
    }
   },
   {
    "name": "ib",
    "query": {
     "query": "label_values(onec_info_connection_status{host=\"$host\"},ib)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mean runtime | $host/$ib",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "repeat": "ib",
   "targets": [
    {
     "expr": "avg(onec_apdex_runtime{host=\"$host\",ib=\"$ib\"}) by (oper)",
     "legendFormat": "{{oper}}"
    }
   ]
  },
  {
   "title": "Last runtime | $host/$ib",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 112 },
   "repeat": "ib",
   "targets": [
    {
     "expr": "avg(onec_apdex_lastoperation_runtime{host=\"$host\",ib=\"$ib\"}) by (oper)",
     "legendFormat": "{{oper}}"
    }
   ]
  },
  {
   "title": "Mean runtime per user | $host/$ib",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 224 },
   "repeat": "ib",
   "targets": [
    {
     "expr": "avg(onec_apdex_runtime{host=\"$host\",ib=\"$ib\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}